# Vitamine D, système immunitaire et réponse antivirale

L'importance du rôle de la vitamine D sur le système immunitaire a
récemment retenu l'attention des chercheurs depuis la découverte de la
coexistence du \ac{VDR} et du \ac{CYP27B1} dans des tissus dont la
fonction n'est pas directement liée à l'homéostasie du calcium
[@Zehnder.2001]. En particulier, l'expression du \ac{CYP27B1} dans les
cellules immunitaires est régulée indépendamment de l'homéostasie du
calcium [@White.2022]. Deux observations principales
suggèrent un rôle de la vitamine D dans le système
immunitaire : le \ac{VDR} est présent dans toutes les
cellules immunitaires, et la présence du \ac{CYP27B1} est induite par
certaines cellules immunes [@Giannini.2022]. De ce fait, cette découverte de la présence de CYP27B1 extra-rénale suggère un rôle local de l'action paracrine ou intracrine du calcitriol [@Hewison.2007; @Bishop.2021].

La vitamine D agit à la fois sur le système immunitaire inné et adaptatif  (\Cref{fig-vd-immune-effect}). En effet, par le biais de la synthèse intracrine du calcitriol par les macrophages et cellules dendritiques, le calcitriol est active en amont et en aval des \acp{PRR} qui jouent un rôle initial dans la réponse innée, stimule la production de peptides antimicrobiens et en particulier la cathélicidine dont il est un puissant inducteur, diminue les concentrations de fer via l'induction de l'hepcidine, augmente l'autophagie permettant de combattre les pathogènes intracellulaires tels que *M. tuberculosis* [@Liu.2006], et les infections virales, et joue un rôle important dans le système adaptatif par une suppression des réponses cellulaires \ac{Th1} et \ac{Th17} tout en promotant une immunotolérance [@Bishop.2021 ; @Ismailova.2022].


Ainsi, plusieurs cellules immunitaires peuvent synthétiser l'enzyme clé
permettant la conversion du \ac{25(OH)D3} en \ac{1,25(OH)2D3}, le
cytochrome \ac{CYP27B1} ou aussi appelée 1α-hydroxylase. L'induction de cette
enzyme concerne des cellules telles que les cellules dendritiques,
monocytes, macrophages, lymphocytes B et T [@Giannini.2022;
@Dankers.2017].

Dans ce contexte, l'enzyme 1α-hydroxylase n'est pas uprégulée par la
\ac{PTH}. Par conséquent, la production de \ac{1,25(OH)2D3} dépend des
niveaux de substrat de \ac{25(OH)D3} et peut être régulée par des signaux
inflammatoires, tels que le \ac{LPS} et les cytokines [@Giannini.2022].



<!-- Je trouve le tableau redondant avec la figure 11 (@fig-vd-immune-effect) -->

<!-- ```{=tex} -->
<!-- \begin{table} -->
<!-- \centering -->
<!-- \caption[Effets de la vitamine D sur le système immunitaire.]{\textbf{Effets de la vitamine D sur le système immunitaire.} Le tableau montre les effets de la vitamine D sur le système immunitaire inné et adaptatif. Globalement, la vitamine D possède un effet immunomodulateur. D'après \textcite{Giannini.2022}.} -->
<!-- \label{tbl:vd-immu} -->
<!-- \begin{tabular}{lc} -->
<!-- \toprule -->
<!-- \textbf{Fonction/Cellules} & \textbf{Effet} \\ -->
<!-- \midrule -->
<!-- \textbf{Immunité Innée} & \\ -->
<!-- Différenciation des macrophages & Augmentation \\ -->
<!-- Elimination des bactéries & Augmentation \\ -->
<!-- Maturation des cellules dendritiques & Diminution \\ -->
<!-- Présentation antigénique & Diminution \\ -->
<!-- \midrule -->
<!-- \textbf{Immunité adaptative} & \\ -->
<!-- Cytokines Th$_1$ & Diminution \\ -->
<!-- Cytokines Th$_2$ & Augmentation \\ -->
<!-- Différentiation des Th${_{17}}$ & Diminution \\ -->
<!-- Différentiation des T\textsubscript{reg} & Augmentation \\ -->
<!-- \addlinespace -->
<!-- \multirow{4}{*}{Lymphocytes B} & Diminution de la prolifération \\ -->
<!-- & Induction de l'apoptose \\ -->
<!-- & Inhibition de la génération des plasmocytes \\ -->
<!-- & Inhibition de la sécrétion des immunoglobulines\\ -->
<!-- \bottomrule -->
<!-- \end{tabular} -->
<!-- \end{table} -->
<!-- ``` -->


## Mécanismes d'action de la vitamine D sur le système immunitaire

Comme nous allons le voir, la vitamine D possède une action globalement
anti-inflammatoire et donc régulatrice de l'inflammation
(\Cref{fig-vd-immune-effect}). Elle agit à la fois sur le système
immunitaire inné et adaptatif. A l'initiation de la réponse
inflammatoire, le calcitriol est essentiel afin de répondre à une
infection. Les effets de la vitamine D ne répriment pas totalement le
système immunitaire mais plutôt induit une modulation immunitaire, en
faisant évoluer le système immunitaire adaptatif vers une tolérance
antigénique, et le système immunitaire inné vers une meilleure
élimination virale et bactérienne [@Martens.2020]. Le calcitriol n'est
donc pas purement anti-inflammatoire mais il contribue à maintenir
l'équilibre entre un état pro- et anti-inflammatoire et est donc capable
de rétablir l'équilibre perturbé [@Dankers.2017].

![**Effets du calcitriol sur la réponse immunitaire.** La
\ac{1,25(OH)2D3} régule à la fois l’immunité innée et l’immunité
adaptative, en potentialisant l’activité antimicrobienne des
macrophages, en diminuant la présentation de l’antigène et en diminuant
les fonctions des lymphocytes B et de certains lymphocytes T. Cependant,
dans des conditions normales, la \ac{1,25(OH)2D3} augmente le phénotype
\ac{Th2} des lymphocytes T helper et l’efficacité des \ac{Treg}. DC,
cellules dendritiques ; APC, cellules présentatrices d'antigènes ;
\acs{TLR}, \acl{TLR} ; \ac{Treg}, \acl{Treg}. D'après
@Cutolo.2014](figures/vd-immune-effect.jpg){#fig-vd-immune-effect
fig-scap="Effets du calcitriol sur la réponse immunitaire."
fig.pos="!htb"}


### Action intracrine et autocrine

Les études suggèrent que la vitamine D délivre ses effets par un mécanisme intracrine ou autocrine et non systémique au sein des tissus non-classiques [@Hewison.2007] et agit localement dans les cellules immunitaires. Un mécanisme intracrine se réfère à un mécanisme impliquant une molécule agissant et produite par la même cellule. 
En effet, trois aspects spécifiques de la \ac{CYP27B1} ont attiré l'attention des chercheurs : l'expression et la régulation dans les tissus non classiques au cours de la physiologie normale ; les effets sur le système immunitaire et les maladies inflammatoires ; l'expression et la fonction dans les tumeurs.

@Hewison.2007 investigue l'idée d'un mécanisme extra-rénal de
\ac{CYP27B1} rapporté dans la littérature et l'efficacité de la réponse du calcitriol endogène dans la modulation de la réponse immune. En représentant les conditions de carence en vitamine D, d'insuffisance en vitamine D et de
suffisance en vitamine D, par une dose de 5, 50 and 150 nM respectivement, l'accumulation de calcitriol dans les cellules dendritiques et macrophages et d'un inhibiteur de CYP27B1, est due à l'activité de l'enzyme 1α-hydroxylase et est augmenté, lorsque les concentrations de calcidiol augmentent, et impacte selon une relation dose-réponse la stimulation de CD14 et la répression de marqueurs de cellule dendritique CD86, CD83 et HLA-DR.

Similairement, l'essai *in vitro* de @Adams.2009 montre que le calcidiol
est nécessaire pour produire la cathélicidine et qu'elle est dépendante
de l'expression du CYP27B1 du macrophage, bien qu'à haute concentration
le calcidiol peut stimuler la production de cathélicidine sans passer
par l'activation des macrophages via le \ac{TLR} De plus, l'expression de
cathélicidine est fortement diminuée lorsque la concentration de
vitamine D administrée est inférieure à 30 ng/mL. En outre, les auteurs
ont observé une absence de corrélation entre les niveaux de
cathélicidine plasmatique et les niveaux de calcidiol plasmatique, ainsi
que la concentration de cathélicidine leucocytaire et la concentration
plasmatique de calcidiol, ce qui suggère que l'effet de la vitamine D
sur la synthèse de la cathélicidine par les cellules immunes est due non
pas à la présence de calcidiol plasmatique mais bien à l'effet local
intracrine des cellules immunes.

@Chun.2010 a montré que la concentration de calcitriol dans les
monocytes était de 10-100 fois plus élevée que dans le plasma, ce qui
suggère que la concentration locale de calcitriol est beaucoup plus
élevée que la concentration plasmatique. Cela suggère que la vitamine D
peut agir de manière intracrine.


L'effet autocrine de la vitamine D sur des lymphocytes T CD4^+^ a été observé par @Chauss.2022. L'administration de calcitriol actif ou calcidiol
conduit aux cellules à réprimer l'\ac{ifng} et augmenter la synthèse
d'\ac{IL-10}, indiquant que les cellules ont acquises la capacité de
métaboliser et de répondre aux métabolites de la vitamine D.
Inversement, lors du KO d'un des gènes concernant la vitamine D tel que
*CTSL*, *VDR* ou *CYP27B1*, une réduction nette en \ac{IL-10} est observée.
Dans l'ensemble les résultats indiquent l'effet d'un mécanisme
intracellulaire autocrine/paracrine de la vitamine D. Des résultats
similaires ont été retrouvé par @Adams.2009 par le KO du *VDR* et
*CYP27B1* et l'expression de la cathélicidine diminuée.


<!-- ### Dose de vitamine D nécessaire à l'immunité -->

<!-- \[*Pourquoi est-ce que 4000 UI est une des doses minimales recommandées -->

<!-- pour un effet immunitaire ? Pourquoi est-ce que le seuil de "40 ng/mL" -->

<!-- est important pour cet effet suffisant ?*\] -->


### Induction de l'immunité innée antimicrobienne

Après l'entrée du calcitriol dans la cellule ou la conversion du calcidiol en calcitriol intracellulaire, l'action du calcitriol 
est médié par l'hétérodimère \ac{VDR}-\ac{RXR} et se fixe sur le \ac{VDRE}, causant la régulation de multiples gènes (\Cref{fig-vd-immune-signaling})
[@Caprio.2017; @Yasmin.2005]. 
Un des mécanismes principaux de l'immunité innée antimicrobienne passe par l'induction de peptides antimicrobiens et en particulier la forte induction de cathélicidine [@Wang.2004]. En effet, la vitamine D stimule l'expression du gène *CAMP* en se liant au \ac{VDRE} situé son promoteur et induit la cathélicidine humaine hCAP-18, clivant ce précurseur en LL-37 par la protéinase 3. Le domaine C-terminal de hCAP18 nommé LL-37, est un peptide antimicrobien qui déstabilise les membranes bactériennes et fongiques et peut empêcher la réplication virale en se liant aux protéines de pointes [@Bishop.2021; @Charoenngam.2020]. De plus, LL-37 est impliqué dans la signalisation, induisant la chimiotaxie et participe à la régénération tissulaire et est capable d'activer les TLR7 et TLR8 activant la cellule dendritique [@Silva.2012].
Le LL-37 est exprimé par les leucocytes, notamment les neutrophiles, les monocytes, les mastocytes, les cellules NK, les lymphocytes T et B. Le LL-37 a également été trouvé dans le plasma, la moelle osseuse, les voies respiratoires, l'intestin, les glandes mammaires, l'épididyme et la peau [@Silva.2012]. De plus, le calcitriol induit également la défensine \mupbeta 2 et par le gène *HBD2* qui contribue à la défense antimicrobienne.

![**Métabolisme de la vitamine D et signalisation immunitaire innée dans le monocyte/macrophage.** Après liaison du calcitriol sur le VDR, le complexe \ac{VDR}-\ac{RXR} se lie sur différentes séquences \ac{VDRE} spécifiques, induisant l'expression de peptides antimicrobiens tel que la cathélicidine et la défensine \mupbeta 2, diminue l'expression de l'hepcidine, favorise l'autophagie, l'expression de \ac{PRR} comme NOD2 et de cytokines IL-1β et IL-8  [@Ismailova.2022].](figures/Ismailova.2022-Vitamin_D_metabolism_and_innate_immune_signaling_in_the_monocyte-macrophage.jpg){#fig-vd-immune-signaling fig-scap="Métabolisme de la vitamine D et signalisation immunitaire innée dans le monocyte/macrophage."}

En réponse au calcitriol, le \ac{VDR} induit l'expression de PRR comme NOD2, TLR2 (\Cref{fig-vd-immune-signaling}).


Le complexe calcitriol-VDR a également pour fonction de supprimer l'expression de *HAMP*, ce qui entraîne une augmentation de l'exportation du fer médiée par la ferroportine. En effet, presque tous les microorganismes utilisent le fer pour leur croissance. De ce fait, la restriction du fer par l'organisme constitue une des réponses afin de lutter contre l'infection ; l'expression de *HAMP* est augmentée lors de stimuli bactériens et viraux [@Bishop.2021]. Lors de la stimulation par le ligand muramyl dipeptide (MDP) généré par la décomposition du peptidoglycane bactérien, NOD2 et IL-1β peuvent augmenter l'expression de *HBD2*, *CAMP* et *IL1B* [@Bishop.2021].


### Effets immunomodulateurs

#### Macrophages et monocytes

Le calcitriol induit le switch phénotypique de macrophage M1 vers M2 par la
régulation positive de l'\ac{IL-10}. Le macrophage M2 est un type de
macrophage ayant un profil anti-inflammatoire contrairement au
macrophage M1 au profil pro-inflammatoire. Le calcitriol inhibe
également des cytokines majeures pro-inflammatoires telles que
l'\ac{IL-6} et le \ac{tnfa} [@Meza-Meza.2022; @Caprio.2017]. Il a
également été démontré que le calcitriol supprime l'expression des
\ac{TLR} sur les monocytes et inhibe la production des cytokines
inflammatoires \ac{IL-2}, l'\ac{IL-6} et l'\ac{IL-17}. La vitamine D
stimule également le signalement cytokinique, avec induction de
chimiokines comme l'IL-8/CXCL8, une chimiokine agissant sur le
neutrophile.


Comme discuté précédemment, les effets du calcitriol ne sont pas toujours de nature pro-inflammatoire. La vitamine D possède un pouvoir pro-inflammatoire dans la réponse initiale de l'inflammation, puis un pouvoir anti-inflammatoire lors de la phase de résolution de l'inflammation [@Dankers.2017]. En effet, la culture de monocytes avec le \ac{LPS} montre une répression de l'\ac{IL-10} pendant les 8 premières heures, suivie d'une induction 48 heures après la réponse initiale [@Matilainen.2010].

![**Représentation schématique des fonctions paracrine et intracrine de
la vitamine D et de ses métabolites et des actions de la
\ac{1,25(OH)2D3} sur les systèmes immunitaires innés et
adaptatifs.** Les macrophages, monocytes et cellules dendritiques sont
capables d'induire le \ac{CYP27B1} afin de métaboliser le calcidiol en
calcitriol, qui va ensuite agir de manière intracrine par le biais de la
translocation de l'hétérodimère \ac{VDR}-\ac{RXR} et agir directement
sur l'expression des facteurs de transcription. Globalement les effets
issus du calcitriol seront liés à l'augmentation de la défense innée notamment par le biais de la cathélicidine, ainsi qu'une
diminution du phénotype mature de la cellule dendritique et une
augmentation du phénotype tolérogène. Par la suite, le calcitriol peut
agir sur les cellules environnantes en favorisant un phénotype
anti-inflammatoire chez les cellules \ac{Th2} et \ac{Treg} ainsi qu'une
diminution de l'activation des cellules \ac{Th1} et \ac{Th17}, et des
cellules B. Abréviation : \ac{1,25(OH)2D3} : \acl{1,25(OH)2D3} ; \ac{25(OH)D3} : \acl{25(OH)D3} ; \ac{ifng} : \acl{ifng} ; IL :
interleukine ; CMH : complexe majeur d'histocompatibilité ; RXR :
\acl{RXR} ; Th1 : T helper 1 ; Th2 : T helper
2 ; Th17 : T helper 17 ; \ac{Treg}, \acl{Treg} ; \ac{tnfa}, \acl{tnfa} ;
\ac{TLR}, \acl{TLR} \ac{VDR}, \acl{VDR}.
[@Charoenngam.2020]](figures/vd-action.jpg){#fig-vd-action
fig-scap="Représentation schématique des fonctions paracrine et intracrine de la vitamine D et de ses métabolites et des actions de la \ac{1,25(OH)2D3} sur les systèmes immunitaires innés et adaptatifs."}


#### Cellules présentatrices d'antigènes et lymphocytes NK

Le calcitriol agit également sur les \ac{CPA} : cellules dendritiques,
macrophages, lymphocytes B, et \ac{NK} en les rendant plus immature et
tolérogéniques, par le biais d'une diminution de l'expression de
\ac{CMH-II} qui leur permet de présenter des antigènes étrangers, ainsi
que l'expression de molécules de co-stimulation (\ac{CD} 40, CD80, CD86)
qui jouent un rôle essentiel dans la stimulation des lymphocytes
(\Cref{fig-vd-action}) [@Charoenngam.2020; @Meza-Meza.2022;
@Caprio.2017]. Ce changement phénotypique s'accompagne donc d'une
diminution de la capacité de présentation d'antigènes et de production
d'\ac{IL-12}, interleukine clé pour la différenciation des lymphocytes T
en Th1, l'activité cytotoxique des lymphocytes \ac{NK} et lymphocytes
CD8^+^, ainsi qu'une augmentation d'\ac{IL-10}, une cytokine clé dans la
régulation du système immunitaire.

En outre, des études expérimentales ont suggéré que la différenciation
et la fonction des lymphocytes \ac{NK} peuvent être modulées par un
traitement au calcitriol [@Charoenngam.2020]. Cependant, le rôle
inducteur ou inhibiteur du calcitriol est encore indéterminé par manque
de données cohérentes.

<!-- #### Fonction endothéliale et perméabilité vasculaire -->

<!-- De nombreuses études expérimentales ont démontré que la vitamine D et -->

<!-- ses métabolites ont la capacité de moduler la fonction endothéliale et -->

<!-- la perméabilité vasculaire par le biais de diverses voies génomiques et -->

<!-- non génomiques. Il a été démontré que la vitamine D~3~, le calcidiol et -->

<!-- le calcitriol stabilisent l'endothélium vasculaire de manière non -->

<!-- génomique, le cholécalciférol étant plus puissante que le calcidiol et -->

<!-- calcitriol à cet égard. En outre, le calcitriol agit comme un régulateur -->

<!-- transcriptionnel de l'oxyde nitrique synthase endothéliale -->

<!-- (\acs{eNOS})\acused{eNOS}, favorisant l'uprégulation de l'expression -->

<!-- génétique de l'\ac{eNOS} et augmentant la production d'\ac{NO} par les -->

<!-- cellules endothéliales. L'apparition rapide en une minute de l'effet du -->

<!-- calcitriol suggère un mécanisme d'action non génomique, soit une action -->

<!-- ne passant pas par une transcription de gènes. L'activation du \ac{VDR} -->

<!-- au niveau de la membrane des cellules endothéliales déclenche des voies -->

<!-- intracellulaires telles que les voies AC/cAMP, IP3 /DAG et PI3K/Akt, ce -->

<!-- qui entraîne une augmentation de la concentration de calcium -->

<!-- intracellulaire et l'activation de la \ac{eNOS}. En outre, des études -->

<!-- ont montré que le calcitriol favorise la formation de jonctions -->

<!-- cellule-cellule et inhibe l'organisation des fibres de stress dans -->

<!-- l'endothélium [@Charoenngam.2020]. -->

<!-- Le calcitriol possède d'autres effets au regard de l'épithélium -->

<!-- intestinal et des cellules de Paneth en augmentant la viabilité des -->

<!-- cellules épithéliales intestinales et atténue les dommages causés à -->

<!-- l'épithélium intestinal par le \ac{LPS} bactérien. La vitamine D est -->

<!-- également capable d'agir non-classiquement par des actions -->

<!-- non-génomique, c'est-à-dire que l'effet de la liaison du calcitriol sur -->

<!-- le VDR ne nécessite pas nécessairement sa translocation dans le noyau -->

<!-- pour avoir des effets et donc l'usage du \ac{VDRE}, mais peut agir -->

<!-- directement par des actions de type protéine-protéine. Cela permet à la -->

<!-- vitamine D de moduler des voies dont les ligands n'interagissent pas -->

<!-- avec la vitamine D, telle que l'inhibition de la kinase \ac{IKKb}, un -->

<!-- régulateur de la voie canonique de \ac{nfkb} passant par le ligand -->

<!-- \ac{tnfa}, une des cytokines pro-inflammatoire clé de la réaction -->

<!-- immunitaire, ou l'interaction avec STAT1 qui permet de moduler cette -->

<!-- voie dont le ligand est l'\ac{ifna}, par la transcription de gène -->

<!-- anti-viraux. Ce mécanisme non-génomique permet à la vitamine D de -->

<!-- moduler entre autre des réponses immunes anti-virales [@Hii.2016 ; -->

<!-- @Chen.2013.IKKb]. -->


La vitamine D joue un rôle essentiel dans la modulation des réponses
immunitaires adaptatives, en particulier des lymphocytes T et B, qui
sont les principales cellules immunitaires de cette composante du
système immunitaire. Les lymphocytes T sont impliqués dans la
reconnaissance des antigènes et la destruction des cellules infectées ou
tumorales, tandis que les lymphocytes B sont impliqués dans la
production d’anticorps. La vitamine D agit sur ces deux types de
lymphocytes en modulant leur fonctionnement et leur activation. La
vitamine D est notamment importante comme élément régulateur entre les
réponses immunitaires pro-inflammatoires et anti-inflammatoires.

Il a été observé que les lymphocytes n’expriment que faiblement le
\ac{VDR} à l’état basal, contrairement aux monocytes, mais fortement
après activation. Les lymphocytes activés expriment également le
\ac{CYP27B1} nécessaire pour convertir le calcidiol en calcitriol
[@Charoengramm.2020]

#### Lymphocytes T

Les lymphocytes T sont composés en plusieurs sous-groupes :

-   les lymphocytes T auxiliaires ou helper CD4^+^ Th1, Th2, Th17. Les
    populations \ac{Th1} et \ac{Th17} ont principalement pour rôle de
    stimuler une réponse cytotoxique, respectivement intracellulaire
    antibactérienne et antiprotozoaire comme le toxoplasme, et
    extracellulaire antibactérienne et fongique. La population \ac{Th2}
    en revanche est centrée sur une stimulation de la réponse humorale
    ou médiée par les anticorps, contre les parasites extracellulaires,
    les bactéries, les allergènes et les toxines, médiée par le biais de
    cytokines causant une forte production d’anticorps, l’activation des
    éosinophiles et de l’inhibition de plusieurs fonctions des
    macrophages

-   les lymphocytes T effecteurs CD8^+^ capables d’induire la mort des
    cellules.

-   les lymphocytes T CD4^+^ régulateurs ou \ac{Treg}, qui ont pour rôle
    de réguler l’inflammation et donc la réponse immunitaire.

lymphocytes T auxiliaires ou helpers \acs{Th} type CD4^+^ (Th~1~, Th~2~,
Th~17~), et les lymphocytes T CD8^+^ qui sont les lymphocytes effecteurs
capables d'induire l'apoptose des cellules. La population Th~1~ et
Th~17~ a principalement pour rôle de stimuler une réponse cytotoxique,
en stimulant respectivement les macrophages pour une réponse
intracellulaire antibactérienne et antiprotozoaire comme le toxoplasme,
et les neutrophiles pour une réponse extracellulaire antibactérienne et
fongique. La population Th~2~ en revanche est centrée sur une
stimulation de la réponse humorale ou médiée par les anticorps, contre
les parasites extracellulaires, les bactéries, les allergènes et les
toxines, médiée par le biais de cytokines causant une forte production
d'anticorps, l'activation des éosinophiles et de l'inhibition de
plusieurs fonctions des macrophages, fournissant ainsi des réponses
protectrices indépendantes des phagocytes [@Cantorna.2015;
@Walker.2018].

Le calcitriol est capable d’induire le changement phénotypique des
sous-populations de lymphocytes T CD4^+^, favorisant le phénotype
\ac{Th2}, au détriment des \ac{Th1} et \ac{Th17}, et l’expression des
cytokines \ac{Th2.} La sous-population \ac{Th2} réprime à son tour les
populations \ac{Th1} et \ac{Th17} [@Meza-Meza.2022], diminuant ainsi
globalement l’activité cytotoxique médiée par ces cellules. De plus, le
calcitriol inhibe la prolifération des lymphocytes Th1 et Th17
[@Cantorna.2015].

Le calcitriol est capable d'induire le changement phénotypique des
sous-populations de lymphocytes T CD4^+^, favorisant un changement de la
population T auxiliaire \ac{Th1} et \ac{Th17} vers la population
\ac{Th2}, en inhibant les cytokines favorisant la population \ac{Th1} et
\ac{Th17} et en augmentant l'expression des cytokines \ac{Th2}. La
sous-population Th~2~ régule à son tour les populations \ac{Th1} et
\ac{Th17} dans un équilibre, diminuant ainsi globalement l'activité
cytotoxique médiée par les cellules, qui est exacerbée dans les maladies
auto-immunes et infections par des pathogènes [@Meza-Meza.2022]. De
plus, le calcitriol en plus de moduler la production des cytokines,
inhibe la prolifération des lymphocytes T [@Cantorna.2015].

Le calcitriol favorise la différenciation des \acp{Treg} à la fois
directement et indirectement par contact avec les \ac{CPA}, où cette
différenciation dépend du contact entre le \ac{CMH-II} des \ac{CPA} et
le récepteur \ac{IL-2} présent sur les lymphocytes [@Charoenngam.2020].
Cependant, les recherches montrent que les lymphocytes FoxP3^+^
\ac{Treg} sont fonctionnellement indépendant de l'expression de VDR pour
effectuer leurs fonctions régulatrices [@Cantorna.2010].

<!-- Concernant les lymphocytes T CD8^+^, les recherches ont observé une -->

<!-- uprégulation du VDR ainsi que de l'enzyme \ac{CYP27B1}, qui reflète une -->

<!-- réponse à une infection. L'administration d'une dose de vitamine D -->

la vitamine D modifie un ratio bas de CD4/CD8 reflétant une activation
immunitaire plus forte à un ratio plus élevé de CD4/CD8, impliquant une
suppression immunitaire [@Charoenngam.2020]. Cependant le mécanisme
exact du calcitriol sur les lymphocytes T CD8^+^ reste encore
indéterminé. Les effets du calcitriol sur la prolifération,
différenciation et fonction seraient probablement lié à l'effet direct
et indirect du VDR.

<!-- De plus, il a été montré que l'action de la vitamine D sur son récepteur -->

<!-- VDR était nécessaire au fonctionnement de deux types de lymphocytes T -->

<!-- qui jouent un rôle régulateur, les lymphocytes \ac{iNKT} et lymphocytes -->

<!-- T CD8αα qui sont intraépithéliaux [@Cheroutre.2008]. La désignation -->

<!-- CD8αα signifie que le co-récepteur CD8 du \ac{TCR} possède deux chaînes -->

<!-- alpha contrairement à l'arrangement usuel αβ. Les cellules NKT sont des -->

<!-- lymphocytes NK qui expriment les récepteurs de la lignée NK, ainsi qu'un -->

<!-- \ac{TCR} de chaîne αβ. Ils seraient parmi les premiers producteurs de -->

<!-- cytokines dans une réponse immunitaire, tels que l'\ac{ifng} et -->

<!-- l'\ac{IL-4}. La majorité des cellules NKT expriment un TCR invariant -->

<!-- \acs{iNKT} [@Cantorna.2010]. -->

<!-- Les lymphocytes T CD8αα possèdent un caractère régulateur contrairement -->

<!-- au lymphocyte CD8αβ classique. Ces lymphocytes sont capables de produire -->

<!-- l'\ac{IL-10} qui régule l'inflammation [@Cantorna.2010]. -->

De ce fait, la présence de calcitriol et du \ac{VDR} est essentielle
pour le caractère régulateur des lymphocytes T, et favorise un
changement phénotypique des lignées lymphocytaires vers une immunité
plus tolérogène en induisant des sous-types de population \ac{Th2},
ainsi que d'autres types de lymphocytes ayant un caractère régulateur.
Les lymphocytes \ac{Treg} FoxP3^+^ ne semblent eux ne pas nécessiter la
présence de vitamine D et du \ac{VDR} pour exercer leurs fonctions
régulatrices [@Cantorna.2010].

#### Lymphocytes B

Le calcitriol joue un rôle immunomodulateur sur les lymphocytes B en
diminuant la réponse immune des lymphocytes B hyperactivés. Cela se
passe directement par l'induction de cytokines anti-inflammatoires chez
les lymphocytes B, telles que l'\ac{IL-10} et le \ac{CCR10}, la
diminution de la formation des lymphocytes B en plasmocytes et des
lymphocytes B mémoires après commutation de classe isotypique, en
modulant le CD40 et donc indirectement le \ac{nfkb}, ainsi que
l'induction de l'apoptose des lymphocytes B activés et les plasmocytes.
Le calcitriol réduit aussi le pouvoir activateur des lymphocytes B par
la régulation à la baisse du CD86 et l'induction du CD74, qui permettent
d'activer les lymphocytes T lorsque le lymphocyte B joue son rôle de
présentateur d'antigènes [@Meza-Meza.2022; @Martens.2020].

<!-- TODO : Doute sur CD74. Lire https://pubmed.ncbi.nlm.nih.gov/25643611/ -->

![**Schéma récapitulatif des effets immunomodulateurs du calcitriol.**
Le calcitriol se fixe sur le \ac{VDR} qui en interagissant avec le
\ac{VDRE} provoque une transcription de gènes régulateurs de l'immunité,
conduisant à des effets globalement favorisant la suppression et
tolérance immunitaire. Cette modulation se manifeste directement par
l'inhibition de facteurs cytokines pro-inflammatoires et l'augmentation
de cytokines anti-inflammatoires ou indirectement en favorisant le
phénotype de cellules immunes immunosuppressives comme les macrophages
de type M2, les sous-types de lymphocytes \ac{Th2} et \ac{Treg} ou le
phénotype tolérogénique des cellules dendritiques
[@Meza-Meza.2022].](figures/calcitriol-immunomodulatory.jpg){#fig-immunomod
fig-scap="Schéma récapitulatif des effets immunomodulateurs du calcitriol."}





## Schéma d'une réponse antivirale classique

La voie des interférons de type I (IFN-1) est centrale dans la réponse
antivirale initiale. Elle permet d’inhiber la réplication virale, de
protéger les cellules non-infectées et de stimuler l’immunité
lymphocytaire antivirale (lymphocytes T CD8, NK). Ces mécanismes
d’immunité innée conduisent à la lyse des cellules infectées et à
l’instauration d’une immunité durable. Dans l'ensemble, ces processus
éliminent le virus, limitent l’atteinte pulmonaire et mènent à une
potentielle guérison.



<!-- TODO : Détailler la réponse -->


## Vitamine D et pouvoir antiviral

@Bishop.2021
@Zdrenghea.2017

Les études montrent globalement que la vitamine D augmente l'immunité
antivirale et en particulier par le biais de la réponse innée immune, et inhibe les
réponses cytokiniques pro-inflammatoires. La vitamine D possède une
implication dans la réponse immunitaire antivirale car de nombreux virus
respiratoires ciblent les cellules épithéliales pulmonaires, qui sont
très sensibles à la présence de vitamine D. Les cellules épithéliales
induisent fortement le \ac{CYP27B1} lors de présence du calcidiol ainsi
que lors de la détection d'ARN viraux double brins [@Bishop.2021]. 

La réponse antivirale innée passe en partie par l'activation des \acp{TLR},
qui cause l'induction du \ac{CYPB27B1} et du \ac{VDR}, médié par l'activation
du TLR2, induisant par la suite l'expression de *CAMP* [@Liu.2006]. La
vitamine D est ainsi un très fort inducteur du gène *CAMP* qui transcrit
le peptide antimicrobien cathélicidine LL-37 capable de se lier aux
\ac{LPS} et de causer la perméabilisation des membranes, et induit
de CD14 [@Hewison.2007]. Le CD14 est le cofacteur du TLR4 qui permet de
reconnaître classiquement le \ac{LPS.} Le calcitriol inhibe également le
signalement du facteur pro-inflammatoire \ac{nfkb} dans les cellules
pulmonaires [@Bishop.2021].

La vitamine D régule la production d'interférons et module la fonction
des cellules immunitaires antivirales ainsi qu'en induisant la
production de peptides antimicrobiens. En effet, elle stimule la
production des AMPs, *CAMP*, *HBD2*, *DEFB4*, dont les deux derniers
éléments contiennent/permettent la génération du complexe \ac{VDRE}
[@Bishop.2021].

Les réponses transcriptionnelles initiales ayant lieu lors d'une
infection virale concernent en particulier les membres de la famille des
facteurs de régulation de l'interféron tels que IRF3 et IRF7, les
membres de la famille AP-1 et \ac{nfkb}. Le calcitriol agit en inhibant
le \ac{nfkb} qui est un puissant pro-inflammatoire, grâce à l'induction
de \ac{IKBa} [@Bishop.2021].

Un mécanisme clé de la réponse antivirale médiée par la vitamine D est
l'induction puissante de l'expression de *CAMP* via le TLR2, gène codant
pour la forme active de la cathélicidine LL-37 qui va à son tour
favoriser la détection des ARN viraux double brins par le \ac{PRR} TLR3.
Le LL-37 peut se lier à l'ARN double brin viral qui se retrouve dans les
endosomes, où est situé le TLR3. Le TLR3 est un \ac{PRR} important dans
la reconnaissance du virus, et enclenche à son tour l'activation du
mécanisme immunitaire inné, en passant par le \ac{nfkb}. Les études
montrent également que le LL-37 possède une activité antivirale directe
qui perturbe les membranes virales [@Bishop.2021]. Une étude montre que
lorsque la concentration de vitamine D est insuffisante, ou lorsqu'un
anticorps anti-LL37 est utilisé afin de bloquer l'effet de la forme
active de la cathélicidine, l'activité antivirale observé dans les
poumons est bloqué, et la supplémentation en vitamine D restaure le
pouvoir antiviral de LL-37 [@Buonfiglio.2017]. Il est intéressant de
noter que cette induction de *CAMP* dépend de la concentration en
calcidiol, et une concentration insuffisante ne permet pas une induction
en CAMP, ce qui renforce l'importance d'une concentration adéquate en
vitamine D appropriée pour le système immunitaire [@White.2022].

Le calcitriol est capable d'induire NOD2 qui induit l'autophagie pour
augmenter la clairance virale. L'autophagie est un mécanisme clé dans le
contrôle de la réplication et l'infection virale, permettant la
dégradation des composants intracellulaires, y compris les protéines
virales et les acides nucléiques. En effet, le calcitriol induit
directement l'expression d'enzymes clés de l'autophagie comme Beclin1 et
PI3KC. en favorisant la cathélicidine qui induit Beclin1. Il peut
également favoriser indirectement l'autophagie en supprimant
l'inhibition de l'autophagie par la voie de signalisation mTOR, et en
stimulant le calcium intracellulaire et le \ac{NO} par le calcitriol
afin d'augmenter l'activité de PI3KC3 [@Bishop.2021].

<!-- - La vitamine D induit également le peptide antimicrobien HBD2 [*Je ne sais pas s'il est utile d'en parler. Oui pour le reste car je compte utiliser en parti ces informations pour expliquer l'action de la vitamine D dans la physiopathologie du COVID-19*] -->




![**Activité antivirale de la vitamine D dans une cellule épithéliale pulmonaire.** Illustration montrant les évènements qui sous-tendent le métabolisme et la signalisation de la vitamine D au cours d'une infection virale et les réponses induites par la 1,25D. Il s'agit notamment de l'induction de l'expression du CAMP et de la suppression des cytokines inflammatoires IL-5 et IFN-γ, ICAM-1 et PAFR par l'intermédiaire de la 1,25D. La forme mature de CAMP, LL37, se lie à l'ARNdb viral, ce qui permet une liaison efficace au TLR3 endosomal, augmentant la signalisation du TLR3 et la clairance virale subséquente. Un autre mécanisme d'élimination virale est l'induction de l'autophagie par le 1,25D [@Ismailova.2022].](figures/Ismailova.2022.-Antiviral_activity_of_vitamin_D_lung_cell.jpg){#fig-vd-antiviral fig-scap="Activité antivirale de la vitamine D dans une cellule épithéliale pulmonaire."}

## Metabolisme de la vitamine D dans le système immunitaire inné

Les cellules immunitaires contrôlent leur propre expression du \ac{VDR} et du \ac{CYP27B1} afin de moduler les effets du calcitriol sur leur activation, en fonction des signaux et du statut inflammatoire de l'environnement. En effet, la \ac{CYP27B1} et le \ac{VDR} peuvent être induites par les monocytes et macrophages en réponse au signalement des \ac{PRR} tel que l'activation de CD14-TLR4 (CD14 étant le corécepteur de TLR4 et une cible d'induction du calcitriol) [@Stoffels.2009], la stimulation de TLR1 et TLR2 [@Liu.2006].
<!-- TODO: Plus de références sur ce paragraphe au dessus. -->

Certaines cytokines sont également capables de réguler l'expression de \ac{CYP27B1} tel que l'\ac{ifng} [@Stoffels.2009] et l'IL-15 en tant qu'intermédiaire après stimulation du TLR1/2 [@Krutzik.2008].

L'expression de \ac{CYP27B1} et de \ac{VDR} contribue à la synthèse de calcitriol grâce au calcidiol circulant, et contribue au fonctionnement du mécanisme immunitaire.

