---
format:
  pdf:
    pdf-engine: lualatex
    papersize: a4
    documentclass: scrreprt
    classoption: listof=totoc # This setting adds list of table and list of figure in table of content
    # Quarto uses a KOMA class by default, so let's follow the pattern and use listof=totoc as an option for the scrreprt class
    # documentclass: memoir # Use this documentclass to have a whole different look and integrated lof/lot in toc
    toc: false # Put to false and use latex to include where you want
    toc-title: Table des Matières
    number-sections: true
    colorlinks: false # Render bibliography links from blue to black 
    pagenumbering: true
    lof: false
    lof-title: Liste des Figures
    lot: false
    lot-title: Liste des Tables
    geometry:
      - top=35mm
      - left=25mm
      - heightrounded
    indent: true
    linestretch: 1.5
    # pandoc_args: !expr acronymsdown::add_filter()
# acronyms:
#   keys:
#     - key: yaml
#       shortname: YAML
#       longname: YAML Ain't Markup Language
crossref:
  lof-title: Liste des Figures
  lot-title: Liste des Tables
link-citations: true
# mainfont: "Times New Roman"
execute:
  echo: false
keep-tex: true
filters:
  - "pandoc-filters/short-captions.lua"
bibliography: ["bibliography/vitamin-d.bib", "bibliography/organization.bib", "bibliography/manual.bib"]
cite-method: biblatex
# biblio-style: "biblatex-chicago" # Doesn't work
csl: "csl/chicago-author-date-fr.csl" # Used for citeproc from pandoc
header-includes:
- \usepackage{setspace} #\setspace{1.5}
- \usepackage{libertine}
- \usepackage[font=small, labelfont=bf, justification=justified, singlelinecheck=true]{caption} # Set figure caption to bold, centered
# Separate chapter from figure numbering : continuous figure numbering.
- \counterwithout{figure}{chapter} 
- \counterwithout{figure}{section}
- \counterwithout{table}{chapter} 
- \counterwithout{table}{section}
- \usepackage[authordate,backend=biber, doi=false,isbn=false]{biblatex-chicago} # Use if biblatex
- \usepackage[french]{babel} # Citation adds "Author ET author"
- \usepackage{bookmark} # To add toc to pdf bookmarks
- \unimathsetup{math-style=french} # {unicode-math} is already loaded, so we choose maths-style=french to have upright greek letters. Use \mupalpha to get alpha.
# - \usepackage[math-style=french]{unicode-math} will not work and somehow conflict with the acronym package
# - \usepackage{upgreek} # alternatively upgreek can be used, \upalpha
- \usepackage{acronym} # Needs suffix and e-TeX
# Use the following to make mixed case acronyms
# See: https://tex.stackexchange.com/a/70894/284278
- \usepackage{etoolbox}
- \makeatletter
- \newif\if@in@acrolist
- \AtBeginEnvironment{acronym}{\@in@acrolisttrue}
- \newrobustcmd{\LU}[2]{\if@in@acrolist#1\else#2\fi}
- \newcommand{\ACF}[1]{{\@in@acrolisttrue\acf{#1}}}
- \usepackage{pdflscape} # Allow \begin{landscape} for figures
- \usepackage{makecell} # Make multiline cell in latex
- \usepackage{multirow} # Required for table and ref
- \usepackage[capitalise,noabbrev, nameinlink]{cleveref} # Allows \cref{} to cite latex table as "Table 3"
# Specify which cross-reference should automatically be bolded : Tables and Figures
# Use \cref{} ; For some reason this only works with this exact disposition :
# Only #1, nameinlink and each of the reference specified. namelink + #1#2#3 would give an error.
- \crefdefaultlabelformat{#2\textbf{#1}#3} # <-- Only #1 in \textbf
- \crefname{table}{\textbf{Table}}{\textbf{Tables}}
- \Crefname{table}{\textbf{Table}}{\textbf{Tables}}
- \crefname{figure}{\textbf{Figure}}{\textbf{Figures}} 
- \Crefname{figure}{\textbf{Figure}}{\textbf{Figures}}
include-before-body: 
- "00-thesis_cover_page.tex"
---

```{r remerciements, child="01-remerciements.qmd"}

```

\pagenumbering{gobble}

{{< pagebreak >}}

```{=tex}
% From package bookmark
\renewcommand{\contentsname}{Table des Matières}
\pdfbookmark[section]{\contentsname}{toc}
\tableofcontents{}
\newpage

% Use the following command to rename the lof with latex :
% \renewcommand*\listfigurename{Liste des Figures}
% However, with Quarto and Pandoc, we could use "lof-title"in "crossref: in the YAML"
\listoffigures
\newpage

% \renewcommand*\listtablename{Liste des Tables}
\listoftables
```
{{< pagebreak >}}

```{r acronyms, child="02-acronyms.qmd"}

```

{{< pagebreak >}}

\pagenumbering{arabic}

```{r introduction, child="03-introduction.qmd"}

```

{{< pagebreak >}}

```{r chapitre_1, child="04-chapitre_1.qmd"}

```

{{< pagebreak >}}

```{r chapitre_2, child="05-chapitre_2.qmd"}

```

{{< pagebreak >}}

```{r chapitre_3, child="06-chapitre_3.qmd"}

```

{{< pagebreak >}}

```{r conclusion, child="07-conclusion.qmd"}

```

{{< pagebreak >}}

# Bibliographie

::: {#refs}
:::
